title: Docker Developer Tools
description: >- # this means to ignore newlines until "baseurl:"
  Dockertools - A Curated List of Developers Tools
show_downloads: true
twitter_username: collabnix
github_username: collabnix
youtube: c/Collabnix
post_search: true
google_analytics:
theme: jekyll-theme-cayman
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
