name: CodeSpell Integration
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: "rouge"
